import { useNavigate } from "react-router-dom";

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen px-6 py-10 bg-white text-gray-800">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-4 text-green-700">Terms and Conditions</h1>
        <p className="mb-4">
          Welcome to <strong>CommuniSafe</strong>. By creating an account, logging in, or using this platform, you agree to be bound by the following Terms and Conditions. Please read them carefully.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">1. Purpose of the Platform</h2>
        <p className="mb-4">
          CommuniSafe is a community safety and visitor management platform designed to streamline announcements, incident reporting, visitor logging, and flood monitoring. The use of this system is for authorized residents, security personnel, and community officials only.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">2. User Responsibilities</h2>
        <p className="mb-4">
          You are responsible for maintaining the confidentiality of your login credentials. Any activity under your account will be considered your responsibility. Users are expected to:
        </p>
        <ul className="list-disc ml-6 mb-4 space-y-1">
          <li>Provide accurate and complete information upon registration.</li>
          <li>Use the platform in a respectful and lawful manner.</li>
          <li>Refrain from spreading false information or misusing any feature.</li>
        </ul>

        <h2 className="text-xl font-semibold mt-6 mb-2">3. Visitor Registration and QR Codes</h2>
        <p className="mb-4">
          QR codes generated by this platform are unique and should only be used for the intended visitor and schedule. Misuse of QR codes may lead to suspension of account privileges.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">4. System Updates and Downtime</h2>
        <p className="mb-4">
          We reserve the right to update, suspend, or modify any feature at any time for maintenance or improvement without prior notice. We will not be liable for any inconvenience caused by such downtimes.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">5. Termination of Access</h2>
        <p className="mb-4">
          Accounts found violating these terms or engaging in any unauthorized activity may be suspended or permanently disabled without prior warning.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">6. Limitation of Liability</h2>
        <p className="mb-4">
          The developers of CommuniSafe shall not be held liable for any damage, loss, or harm caused by the misuse of the platform or incorrect information provided by users.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">7. Changes to Terms</h2>
        <p className="mb-4">
          These Terms may be revised at any time. You are encouraged to review this page regularly to stay informed.
        </p>

        <h2 className="text-xl font-semibold mt-6 mb-2">8. Contact Information</h2>
        <p className="mb-4">
          For questions or clarifications, please contact us at: <a href="mailto:support@communisafe.app" className="text-green-600 underline">support@communisafe.app</a>.
        </p>

        <p className="mt-8 text-sm text-gray-500">Last Updated: April 2025</p>

        
        <div className="mt-10 text-center">
          <button
            onClick={() => navigate("/login")}
            className="bg-green-600 hover:bg-green-700 text-white px-4 py-1.5 text-xs rounded-md shadow-sm transition"
          >
            Okay, I’ve read this — Back to Login
          </button>
        </div>
      </div>
    </div>
  );
}
